image: node:latest

variables:
  PUBLIC_URL: /mp2

cache:
  paths:
  - node_modules

stages:
  - deploy

pages:
  stage: deploy

  script:
    - npm install        # Install all dependencies
    - npm run build      # Build for prod
    - cat build/index.html # Print out index.html before changing path
    - sed -i 's%/mp2%.%g' build/index.html # Fix static path by changing path to relative
    - cat build/index.html # Print out index.html to verify path is correct
    - mv public _public  # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    - mv build public    # Move build files to public dir for Gitlab Pages

  artifacts:
    paths:
    - public

  only:
    - main